export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 20;
export const PASSWORD_REGEX = /^[\w\d!@#$%^&*()\-_=+[\]{};:'",.<>/?\\|`~]+$/;
export const USERNAME_MIN_LENGTH = 5;
export const USERNAME_MAX_LENGTH = 12;
export const USERNAME_REGEX = /^[a-zA-Z0-9_]+$/;
export const FIRST_NAME_MIN_LENGTH = 2;
export const FIRST_NAME_MAX_LENGTH = 50;
export const FIRST_NAME_REGEX = /^[\p{L}][\p{L}'\- ]{0,48}[\p{L}]$/u;
export const LAST_NAME_MIN_LENGTH = 2;
export const LAST_NAME_MAX_LENGTH = 50;
export const LAST_NAME_REGEX = /^[\p{L}][\p{L}'\- ]{0,48}[\p{L}]$/u;
